# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeneratorTiles
                                 A QGIS plugin
 To split and ecw file with specific grid turn it into mbtiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-03-08
        copyright            : (C) 2023 by Kholil Rahman
        email                : its@ahmadk.me
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Kholil Rahman'
__date__ = '2023-03-08'
__copyright__ = '(C) 2023 by Kholil Rahman'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeneratorTiles class from file GeneratorTiles.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .generator_tiles import GeneratorTilesPlugin
    return GeneratorTilesPlugin()
